app/player/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, Optional

from ..lang import WORDINGS
from ..models import Player


class CreatePlayerForm(FlaskForm):
    first_name = StringField(
        WORDINGS.PLAYER.FIRST_NAME,
        validators=[
            Optional()
        ]
    )
    last_name = StringField(
        WORDINGS.PLAYER.LAST_NAME,
        validators=[
            DataRequired(message=WORDINGS.COMMON.MISSING_FIELD)
        ]
    )

    def validate(self, extra_validators=None):
        rv = FlaskForm.validate(self, extra_validators)
        if not rv:
            return False
        if (Player.query.filter_by(first_name=self.first_name.data)
                .filter_by(last_name=self.last_name.data).first()):
            self.first_name.errors.append("")
            self.last_name.errors.append(WORDINGS.PLAYER.PLAYER_ALREADY_EXISTS)
            return False
        return True


class EditPlayerForm(FlaskForm):
    first_name = StringField(
        WORDINGS.PLAYER.FIRST_NAME,
        validators=[
            Optional()
        ]
    )
    last_name = StringField(
        WORDINGS.PLAYER.LAST_NAME,
        validators=[
            DataRequired(message=WORDINGS.COMMON.MISSING_FIELD)
        ]
    )

    def __init__(self, player, *args, **kwargs):
        super(EditPlayerForm, self).__init__(*args, **kwargs)
        self.player = player

    def validate(self, extra_validators=None):
        rv = FlaskForm.validate(self, extra_validators)
        if not rv:
            return False
        if ((self.first_name.data != self.player["first_name"]
             or self.last_name.data != self.player["last_name"])
                and (Player.query.filter_by(first_name=self.first_name.data)
                        .filter_by(last_name=self.last_name.data).first())):
            self.first_name.errors.append("")
            self.last_name.errors.append(WORDINGS.PLAYER.PLAYER_ALREADY_EXISTS)
            return False
        return True

app/player/forms/__init__.py
from .create_player import CreatePlayerForm
from .edit_player import EditPlayerForm

app/player/forms/create_player.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, Optional

from ..domain import does_player_exist
from ...lang import WORDINGS


class CreatePlayerForm(FlaskForm):
    first_name = StringField(
        WORDINGS.PLAYER.FIRST_NAME,
        validators=[
            Optional()
        ]
    )
    last_name = StringField(
        WORDINGS.PLAYER.LAST_NAME,
        validators=[
            DataRequired(message=WORDINGS.COMMON.MISSING_FIELD)
        ]
    )

    def validate(self, extra_validators=None):
        rv = FlaskForm.validate(self, extra_validators)
        if not rv:
            return False

        if does_player_exist(self.first_name.data, self.last_name.data):
            self.first_name.errors.append("")
            self.last_name.errors.append(WORDINGS.PLAYER.PLAYER_ALREADY_EXISTS)
            return False

        return True

app/player/forms/edit_player.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, Optional

from ..domain import does_player_exist
from ...lang import WORDINGS


class EditPlayerForm(FlaskForm):
    first_name = StringField(
        WORDINGS.PLAYER.FIRST_NAME,
        validators=[
            Optional()
        ]
    )
    last_name = StringField(
        WORDINGS.PLAYER.LAST_NAME,
        validators=[
            DataRequired(message=WORDINGS.COMMON.MISSING_FIELD)
        ]
    )

    def __init__(self, player, *args, **kwargs):
        super(EditPlayerForm, self).__init__(*args, **kwargs)
        self.player = player

    def validate(self, extra_validators=None):
        rv = FlaskForm.validate(self, extra_validators)
        if not rv:
            return False

        if not self.has_first_name_changed() and not self.has_last_name_changed():
            return True

        if does_player_exist(self.first_name.data, self.last_name.data):
            self.first_name.errors.append("")
            self.last_name.errors.append(WORDINGS.PLAYER.PLAYER_ALREADY_EXISTS)
            return False

        return True

    def has_first_name_changed(self):
        return self.first_name.data != self.player["first_name"]

    def has_last_name_changed(self):
        return self.last_name.data != self.player["last_name"]

app/player/__init__.py
from flask import Blueprint

bp = Blueprint('player', __name__)

from . import views

app/player/domain/__init__.py
from .does_player_exist import does_player_exist

app/player/views/__init__.py
from .create_player import create_player
from .delete_player import delete_player
from .edit_player import edit_player
from .view_players import view_players

app/player/views/create_player.py
from flask import render_template, redirect, request, url_for

from .. import bp
from ..forms import CreatePlayerForm
from ...decorators import manager_required
from ...lang import WORDINGS
from ...models import db, Player
from ...utils import display_info_toast


@bp.route("/create", methods=["GET", "POST"])
@manager_required
def create_player():
    form = CreatePlayerForm(request.form)
    if form.validate_on_submit():
        player = Player(
            first_name=form.first_name.data,
            last_name=form.last_name.data
        )
        db.session.add(player)
        db.session.commit()
        display_info_toast(WORDINGS.PLAYER.PLAYER_CREATED.format(player.get_full_name()))
        return redirect(url_for(".create_player"))
    else:
        return render_template(
            "player/create_player.html",
            title=WORDINGS.PLAYER.CREATE_PLAYER,
            form=form
        ) 

app/player/views/delete_player.py
import datetime

from flask import redirect, url_for

from .. import bp
from ...decorators import manager_required
from ...lang import WORDINGS
from ...models import db, Player
from ...utils import display_info_toast


@bp.route("/<player_id>/delete")
@manager_required
def delete_player(player_id):
    player = Player.query.get_or_404(player_id)
    player.deleted_at = datetime.datetime.now()
    db.session.add(player)
    db.session.commit()
    display_info_toast(WORDINGS.PLAYER.PLAYER_DELETED.format(player.get_full_name()))
    return redirect(url_for(".view_players")) 

app/player/views/edit_player.py
from flask import render_template, redirect, request, url_for

from .. import bp
from ..forms import EditPlayerForm
from ...decorators import manager_required
from ...lang import WORDINGS
from ...models import db, Player
from ...utils import display_info_toast


@bp.route("/<player_id>/edit", methods=["GET", "POST"])
@manager_required
def edit_player(player_id):
    player = Player.query.get_or_404(player_id)
    title = player.get_full_name()
    form = EditPlayerForm(request.form)
    if request.method == "GET":
        form.first_name.data = player.first_name
        form.last_name.data = player.last_name
    if form.validate_on_submit():
        player.first_name = form.first_name.data
        player.last_name = form.last_name.data
        db.session.add(player)
        db.session.commit()
        display_info_toast(WORDINGS.PLAYER.PLAYER_UPDATED.format(player.get_full_name()))
        return redirect(
            url_for(
                ".edit_player",
                player_id=player_id
            )
        )
    else:
        return render_template(
            "player/edit_player.html",
            title=title,
            form=form,
            player=player
        ) 

app/player/views/view_players.py
from flask import render_template, request, current_app

from .. import bp
from ...decorators import manager_required
from ...lang import WORDINGS
from ...models import Player


@bp.route("/all")
@manager_required
def view_players():
    page = request.args.get("page", 1, type=int)
    pagination = (Player.query.order_by(Player.last_name, Player.first_name)
                  .filter(Player.deleted_at.is_(None))
                  .paginate(page=page, per_page=current_app.config["PLAYERS_PER_PAGE"], error_out=False))

    return render_template(
        "player/view_players.html",
        title=WORDINGS.PLAYER.PLAYERS,
        pagination=pagination
    ) 

app/templates/player/create_player.html
{% extends "base.html" %}

{% block content %}

<div class="panel panel-default">

    <div class="panel-heading">
        <h3 class="panel-title">Créer un joueur</h3>
    </div>

    <form action="{{ url_for('player.create_player') }}" class="form-horizontal" method="POST">
        {{ form.hidden_tag() }}

        <div class="panel-body">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">

                    <div class="form-group {% if form.first_name.errors %} has-error {% endif %}">
                        {{form.first_name.label()}}
                        <div>
                            {{form.first_name(class="form-control")}}
                        </div>
                        <p class="help-block">
                            {{ form.first_name.errors[0] }}
                    </div>

                    <div class="form-group {% if form.last_name.errors %} has-error {% endif %}">
                        {{form.last_name.label()}}
                        <div>
                            {{form.last_name(class="form-control")}}
                        </div>
                        <p class="help-block">
                            {{ form.last_name.errors[0] }}
                    </div>

                    <div class="form-group">
                        <button class="btn btn-success" type="submit">Valider</button>
                    </div>

                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

app/templates/player/edit_player.html
{% extends "base.html" %}

{% block content %}

<div class="panel panel-default">

    <div class="panel-heading">
        <h3 class="panel-title">Editer le joueur {{ player.get_full_name() }}</h3>
    </div>

    <form action="{{ url_for('player.edit_player', player_id=player.id) }}" class="form-horizontal" method="POST">
        {{ form.hidden_tag() }}

        <div class="panel-body">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">

                    <div class="form-group {% if form.first_name.errors %} has-error {% endif %}">
                        {{form.first_name.label()}}
                        <div>
                            {{form.first_name(class="form-control")}}
                        </div>
                        <p class="help-block">
                            {{ form.first_name.errors[0] }}
                    </div>

                    <div class="form-group {% if form.last_name.errors %} has-error {% endif %}">
                        {{form.last_name.label()}}
                        <div>
                            {{form.last_name(class="form-control")}}
                        </div>
                        <p class="help-block">
                            {{ form.last_name.errors[0] }}
                    </div>

                    <div class="form-group">
                        <button class="btn btn-success" type="submit">Valider</button>
                    </div>

                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

app/templates/player/view_players.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block content %}


<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Liste des joueurs</h3>
    </div>

    <div class="panel-body">
        {% if current_user.is_manager() %}
            <div class="btn-group" role="group">
                <a class="btn btn-secondary btn-outline"
                   href="{{ url_for('.create_player') }}">
                   <span class="fa fa-pencil"></span>
                    Nouveau joueur
                </a>
            </div>
        {% endif %}

        <div class="table">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Prénom</th>
                        <th>Nom</th>
                        {% if current_user.is_manager() %}
                            <th>Actions</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for player in pagination.items %}
                        <tr>
                            <td>{{ player.first_name }}</td>
                            <td>{{ player.last_name }}</td>
                            {% if current_user.is_manager() %}
                                <td>
                                    <div class="btn-group" role="group">
                                        <a class="btn btn-warning"
                                       href="{{ url_for('.edit_player', player_id=player.id) }}">
                                            <span class="fa fa-pencil"></span>
                                            Editer
                                        </a>
                                    </div>
                                    <div class="btn-group" role="group">
                                        <a class="btn btn-danger"
                                       href="{{ url_for('.delete_player', player_id=player.id) }}">
                                            <span class="fa fa-trash"></span>
                                            Supprimer
                                        </a>
                                    </div>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        {{ macros.pagination_widget(pagination, '.view_players') }}

    </div>
</div>




{% endblock %}