app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, SelectField, TextAreaField
from wtforms.validators import DataRequired, Email, Length, ValidationError, Optional

from ..lang import WORDINGS
from ..models import User, Role


class EditProfileAdminForm(FlaskForm):
    email = StringField(
        WORDINGS.AUTH.EMAIL,
        validators=[
            DataRequired(),
            Length(1, 64),
            Email()
        ]
    )
    username = StringField(
        WORDINGS.AUTH.USERNAME,
        validators=[
            DataRequired(),
            Length(1, 64)
        ]
    )
    confirmed = BooleanField(WORDINGS.MAIN.CONFIRMED)
    role = SelectField(WORDINGS.MAIN.ROLE, coerce=int)

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)

        self.role.choices = [
            (role.id, role.name)
            for role in Role.query.order_by(Role.name).all()
        ]
        self.user = user

    def validate_email(self, field):
        if field.data != self.user.email and User.query.filter_by(email=field.data).first():
            raise ValidationError(WORDINGS.AUTH.EMAIL_ALREADY_TAKEN)

    def validate_username(self, field):
        if field.data != self.user.username and User.query.filter_by(username=field.data).first():
            raise ValidationError(WORDINGS.AUTH.USERNAME_ALREADY_TAKEN)


class ContactForm(FlaskForm):
    email = StringField(
        WORDINGS.AUTH.EMAIL,
        validators=[
            Optional(),
            Length(1, 64),
            Email()
        ]
    )
    message = TextAreaField(
        WORDINGS.MAIN.MESSAGE,
        validators=[
            DataRequired(),
            Length(max=1000)
        ]
    )

app/main/forms/__init__.py
from .contact import ContactForm
from .edit_profile_admin import EditProfileAdminForm

app/main/forms/contact.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired, Email, Length, Optional

from ...lang import WORDINGS


class ContactForm(FlaskForm):
    email = StringField(
        WORDINGS.AUTH.EMAIL,
        validators=[
            Optional(),
            Length(1, 64),
            Email()
        ]
    )
    message = TextAreaField(
        WORDINGS.MAIN.MESSAGE,
        validators=[
            DataRequired(),
            Length(max=1000)
        ]
    ) 

app/main/forms/edit_profile_admin.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, SelectField
from wtforms.validators import DataRequired, Email, Length, ValidationError

from ...lang import WORDINGS
from ...models import User, Role


class EditProfileAdminForm(FlaskForm):
    email = StringField(
        WORDINGS.AUTH.EMAIL,
        validators=[
            DataRequired(),
            Length(1, 64),
            Email()
        ]
    )
    username = StringField(
        WORDINGS.AUTH.USERNAME,
        validators=[
            DataRequired(),
            Length(1, 64)
        ]
    )
    confirmed = BooleanField(WORDINGS.MAIN.CONFIRMED)
    role = SelectField(WORDINGS.MAIN.ROLE, coerce=int)

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)

        self.role.choices = [
            (role.id, role.name)
            for role in Role.query.order_by(Role.name).all()
        ]
        self.user = user

    def validate_email(self, field):
        if field.data != self.user.email and User.query.filter_by(email=field.data).first():
            raise ValidationError(WORDINGS.AUTH.EMAIL_ALREADY_TAKEN)

    def validate_username(self, field):
        if field.data != self.user.username and User.query.filter_by(username=field.data).first():
            raise ValidationError(WORDINGS.AUTH.USERNAME_ALREADY_TAKEN) 

app/lang/main.py
from types import SimpleNamespace

wordings = SimpleNamespace(
    CONFIRMED="Confirmé",
    FAQ="FAQ",
    HOMEPAGE="Accueil",
    MESSAGE="Message",
    MESSAGE_SENT="Votre message a bien été envoyé.",
    ROLE="Rôle",
    USERS="Utilisateurs",
)

app/main/__init__.py
from flask import Blueprint

from ..models import Permission

bp = Blueprint('main', __name__)


@bp.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)


from . import views, errors

app/main/views/__init__.py
from .contact import contact
from .edit_profile_admin import edit_profile_admin
from .faq import faq
from .index import index
from .landing import landing
from .view_user import view_user
from .view_users import view_users
from .view_validated_users import view_validated_users

app/main/views/contact.py
from flask import render_template, redirect, url_for, current_app
from flask_login import current_user

from .. import bp
from ..forms import ContactForm
from ...email import send_email
from ...lang import WORDINGS
from ...utils import display_info_toast


@bp.route("/contact", methods=['GET', 'POST'])
def contact():
    title = "Contact"
    form = ContactForm()
    if form.validate_on_submit():
        message = form.message.data
        if current_user and hasattr(current_user, "username"):
            sender = current_user.username
        else:
            sender = "un utilisateur non connecté"
        send_email(
            to=current_app.config["ADMIN_JDL"],
            subject="Nouveau message de la part de {}".format(sender),
            template="email/contact",
            message=message,
            email=form.email.data,
            user=current_user
        )
        display_info_toast(WORDINGS.MAIN.MESSAGE_SENT)
        return redirect(url_for(".contact"))

    return render_template(
        "main/contact.html",
        form=form,
        title=title
    ) 

app/main/views/edit_profile_admin.py
from flask import render_template, request, redirect, url_for
from flask_login import login_required

from .. import bp
from ..forms import EditProfileAdminForm
from ...decorators import admin_required
from ...lang import WORDINGS
from ...models import db, User, Role
from ...utils import display_success_toast


@bp.route("/edit-profile/<int:user_id>", methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(user_id):
    title = "Modification de profil"
    user = User.query.get_or_404(user_id)
    form = EditProfileAdminForm(user=user)

    if request.method == "GET":
        form.email.data = user.email
        form.username.data = user.username
        form.confirmed.data = user.confirmed
        form.role.data = user.role
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        db.session.add(user)
        display_success_toast(WORDINGS.AUTH.PROFILE_UPDATED)
        return redirect(
            url_for(
                ".view_user",
                user_id=user.id
            )
        )

    form.email.data = user.email
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id

    return render_template(
        "main/edit_profile.html",
        form=form,
        user=user,
        title=title
    ) 

app/main/views/faq.py
from flask import render_template

from .. import bp
from ...lang import WORDINGS


@bp.route("/faq")
def faq():
    return render_template(
        "main/faq.html",
        title=WORDINGS.MAIN.FAQ
    ) 

app/main/views/index.py
from flask import render_template

from .. import bp
from ...lang import WORDINGS
from ...models import Tournament, Ranking
from ...tournament import domain as tournament_domain


@bp.route("/index")
def index():
    tournaments = Tournament.get_recent_tournaments(20)
    current_tournament = tournament_domain.get_current_tournament()
    latest_tournament = Tournament.get_latest_finished_tournament()
    race_ranking = Ranking.get_historical_race_ranking(latest_tournament.id).limit(20)

    return render_template(
        "main/index.html",
        title=WORDINGS.MAIN.HOMEPAGE,
        tournaments=tournaments,
        current_tournament=current_tournament,
        race_ranking=race_ranking
    ) 

app/main/views/landing.py
from flask import redirect, render_template, url_for
from flask_login import current_user

from .. import bp
from ...lang import WORDINGS


@bp.route("/")
def landing():
    if current_user.is_authenticated:
        return redirect(url_for(".index"))
    return render_template(
        "main/homepage.html",
        title=WORDINGS.MAIN.HOMEPAGE
    ) 

app/main/views/view_user.py
from flask import render_template, request, current_app
from flask_login import login_required

from .. import bp
from ...lang import WORDINGS
from ...models import User, Participant, Tournament, TournamentStatus, Ranking


@bp.route("/user/<user_id>")
@login_required
def view_user(user_id):
    user = User.query.get_or_404(user_id)
    title = "Profil de {}".format(user.username)
    page = request.args.get("page", 1, type=int)
    pagination = (user.participants_sorted()
                  .join(Tournament, Tournament.id == Participant.tournament_id)
                  .filter(Tournament.status == TournamentStatus.FINISHED)
                  .filter(Tournament.deleted_at.is_(None))
                  .order_by(Tournament.started_at.desc())
                  .paginate(page=page, per_page=current_app.config["TOURNAMENTS_PER_PAGE"], error_out=False))

    rankings = Ranking.generate_chart(user_id)

    series = [
        {
            "name": "Classement annuel",
            "data": [
                {
                    "x": int(t.started_at.strftime("%s")) * 1000,
                    "y": t.annual_ranking or "null",
                    "tournament_name": t.name
                }
                for t in rankings
            ]
        },
        {
            "name": WORDINGS.RANKING.RACE_RANKING,
            "data": [
                {
                    "x": int(t.started_at.strftime("%s")) * 1000,
                    "y": t.year_to_date_ranking or "null",
                    "tournament_name": t.name
                }
                for t in rankings
            ]
        }
    ]

    return render_template(
        "main/view_user.html",
        title=title,
        user=user,
        series=series,
        pagination=pagination
    ) 

app/main/views/view_users.py
from flask import render_template, request, current_app

from .. import bp
from ...decorators import manager_required
from ...lang import WORDINGS
from ...models import User


@bp.route("/user/all")
@manager_required
def view_users():
    page = request.args.get("page", 1, type=int)
    pagination = (User.query.order_by(User.username)
                  .filter(User.deleted_at == None)
                  .paginate(page=page, per_page=current_app.config["USERS_PER_PAGE"], error_out=False))
    return render_template(
        "main/view_users.html",
        title=WORDINGS.MAIN.USERS,
        pagination=pagination,
        page_start_index=(page - 1) * current_app.config["USERS_PER_PAGE"]
    ) 

app/main/views/view_validated_users.py
from flask import render_template, request, current_app

from .. import bp
from ...decorators import manager_required
from ...lang import WORDINGS
from ...models import User


@bp.route("/user/validated")
@manager_required
def view_validated_users():
    page = request.args.get("page", 1, type=int)
    pagination = (User.query.order_by(User.username)
                  .filter(User.deleted_at == None)
                  .filter(User.confirmed)
                  .paginate(page=page, per_page=current_app.config["USERS_PER_PAGE"], error_out=False))

    return render_template(
        "main/view_users.html",
        title=WORDINGS.MAIN.USERS,
        pagination=pagination,
        page_start_index=(page - 1) * current_app.config["USERS_PER_PAGE"]
    ) 

app/templates/main/contact.html
{% extends "base.html" %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Contact</h3>
    </div>

    <div class="panel-body">
        <p>Un bug à signaler ? Une remarque, une question, une proposition d'amélioration ?</p>
        <p>Envoyez-nous un message : jeudelorgue [at] gmail.com</p>
    </div>
</div>

{% endblock %}

app/templates/main/edit_profile.html
{% extends "base.html" %}

{% block content %}

<div class="panel panel-default">

    <div class="panel-heading">
        <h3 class="panel-title">Modification de profil</h3>
    </div>

    <form action="{{ url_for('main.edit_profile_admin', user_id=user.id) }}" class="form-horizontal" method="POST">
        {{ form.hidden_tag() }}

        <div class="panel-body">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">

                    <div class="form-group {% if form.email.errors %} has-error {% endif %}">
                        {{form.email.label()}}
                        <div>
                            {{form.email(class="form-control")}}
                        </div>
                        <p class="help-block">
                            {{ form.email.errors[0] }}
                    </div>

                    <div class="form-group {% if form.username.errors %} has-error {% endif %}">
                        {{form.username.label()}}
                        <div>
                            {{form.username(class="form-control")}}
                        </div>
                        <p class="help-block">
                            {{ form.username.errors[0] }}
                    </div>

                    <div class="form-group {% if form.role.errors %} has-error {% endif %}">
                        {{form.role.label()}}
                        <div>
                            {{ form.role(class="form-control") }}
                        </div>
                        <p class="help-block">
                            {{ form.role.errors[0] }}
                    </div>

                    <div class="form-group {% if form.confirmed.errors %} has-error {% endif %}">
                        <div class="checkbox">
                            <label>{{ form.confirmed }} {{ form.confirmed.label}}</label>
                        </div>
                        <p class="help-block">
                            {{ form.confirmed.errors[0] }}
                    </div>

                    <div class="form-group">
                        <button class="btn btn-success" type="submit">Valider</button>
                    </div>

                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

app/templates/main/faq.html
{% extends "base.html" %}

{% block content %}

<div class="panel panel-default">

    <div class="panel-heading">
        <h3 class="panel-title">FAQ</h3>
    </div>

    <div class="panel-body">

        <ul>
            <li>
               <h4><span class="fa fa-chevron-right"></span>
               Comment participer à un tournoi ?</h4>
               <p>Sur la page du tournoi, cliquez sur "M'inscrire". Si ce bouton n'est pas présent, les inscriptions sont fermées ou ne sont pas encore ouvertes.</p>
            </li>
            <br>
            <li>
               <h4><span class="fa fa-chevron-right"></span>
               Comment remplir mon tableau ?</h4>
               <p>Une fois inscrit au tournoi, cliquez sur "Remplir mon tableau". Pour pronostiquer chaque match, cliquez sur le nom du joueur qui va l'emporter selon vous. Une fois que vous avez pronostiqué tous les matchs, cliquez sur "Valider".</p>
            </li>
            <br>
            <li>
               <h4><span class="fa fa-chevron-right"></span>
               C'est super long de remplir un tableau, je peux le faire en plusieurs fois ?</h4>
               <p>Oui, vous pouvez remplir une partie du tableau, valider, puis revenir plus tard pour compléter le reste.</p>
            </li>
            <br>
            <li>
               <h4><span class="fa fa-chevron-right"></span>
               Qu'est ce que le coefficient de risque ?</h4>
               <p>Le coefficient de risque est un indicateur qui sert à départager les participants en favorisant ceux qui ont pris le plus de risques, c'est-à-dire qui ont fait des pronostics différents des autres participants.</p>
               <p>Pour un participant donné, il est calculé en faisant la somme (match par match, pondérée par le nombre de points en jeu sur le match) des participants ayant fait un pronostic différent.</p>
               <p>Plus votre coefficient de risque est élevé, mieux vous serez placé en cas d'égalité.</p>
            </li>
            <br>
            <li>
               <h4><span class="fa fa-chevron-right"></span>
               Comment les points ATP sont-ils attribués ?</h4>
               <p>Les points sont attribués à la fin du tournoi en fonction de 3 éléments :</p>
                <ul>
                  <li><span class="fa fa-chevron-right"></span> Le nombre de points attribué au vainqueur (1000 pour un ATP 1000, 2000 pour un Grand Chelem)</li>
                  <li><span class="fa fa-chevron-right"></span> Le nombre de points attribué au dernier (10)</li>
                  <li><span class="fa fa-chevron-right"></span> Le nombre de participants au tournoi.</li>
                </ul>

              <p>Les points attibués aux joueurs dans un Grand Chelem sont calculés avec <a href="http://image.noelshack.com/fichiers/2018/10/2/1520370404-formule.png">cette formule</a>. En ATP 1000, le 180 est remplacé par 90 et le 200 par 100.</p>
              <p>90 % environ du total de points est calculé en fonction du classement obtenu dans le JDL en question, suivant une exponentielle (la première partie de la formule ci-dessus).</p>
              <p>10 % environ du total de points est calculé en fonction du score obtenu dans le JDL en question, suivant une fonction affine (deuxième partie de la formule).</p>
            </li>

        </ul>

        {% if current_user.is_manager() %}
        <br>
        <h3>FAQ du manager de tournois</h3>
        <br>
        <ul>
            <li>
               <h4><span class="fa fa-chevron-right"></span>
               Comment créer un tournoi ?</h4>
               <p>Dans la barre de navigation, cliquez sur "Admin > Créer un tournoi".
               Renseignez un nom et une catégorie de tournoi, et une date de début pour le tournoi (date limite d'inscription). </p>
               <p>Cette date est uniquement indicative, pour le moment la fermeture des inscriptions se fait à la main par le manager du tournoi.</p>
            </li>
            <br>
            <li>
               <h4><span class="fa fa-chevron-right"></span>
               Comment créer le tableau du tournoi ?</h4>
               <p>Sur la page du tournoi, cliquez sur "Créer le tableau". </p>
               <p>Remplissez un par un les joueurs du tableau en les sélectionnant dans la liste des joueurs disponibles. Vous pouvez spécifier un statut particulier (Q, WC, SE, LL) dans la 2ème colonne, et les numéros des têtes de série dans la 3ème.</p>
               <p>Si un joueur du tableau n'est pas disponible dans la liste, vous pouvez cliquer sur "Ajouter un joueur". La page permettant de créer un joueur s'ouvre dans un nouvel onglet. Créer alors tous les joueurs nécessaires.</p>
               <p>Une fois que c'est fait, revenez à l'onglet de création du tableau. Cliquez sur "Valider" en bas de la page pour sauvegarder l'état actuel du tableau. Vous êtes redirigé vers la page du tournoi. Cliquez alors sur "Modifier le tableau de départ", vous pourrez continuer à remplir le tableau, les joueurs que vous avez créés apparaitront dans la liste de joueurs disponibles.</p>
            </li>
            <br>
            <li>
               <h4><span class="fa fa-chevron-right"></span>
               Comment gérer les qualifiés ?</h4>
               <p>Si certains joueurs du tableau de sont pas encore connus, laissez le champ "Joueur" vide. Le nom sera automatiquement remplacé par "Qualifié N".  </p>
               <p>Une fois le nom d'un qualifié connu, vous pourrez modifier le tableau de départ en conséquence. La modification sera prise en compte dans les tableaux des participants ayant déjà fait un pronostic.</p>
            </li>
            <br>
            <li>
               <h4><span class="fa fa-chevron-right"></span>
               Une fois le tournoi lancé, comment rentrer les résutats des matchs ?</h4>
               <p>Sur la page du tournoi, cliquez sur "Mettre à jour le tableau".</p>
               <p>Cliquez sur le nom d'un joueur pour le faire avancer au tour suivant.</p>
               <p>Si vous avez cliqué par erreur sur un joueur, pas de panique, control-cliquez sur le nom du vainqueur pour effacer le contenu de la case.</p>
            </li>
            <br>
            <li>
               <h4><span class="fa fa-chevron-right"></span>
               Que faire à la fin du tournoi ?</h4>
               <p>Lorsque le résultat du dernier match est validé, cliquez sur "Clôturer le tournoi".</p>
               <p>Les scores finaux seront calculés et les points ATP attribués aux participants.</p>
            </li>
        </ul>

        {% endif %}

    </div>
</div>


{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default panel-table">

            <div class="panel-heading">
                <a href="{{ url_for('ranking.race_ranking') }}">
                    <h3 class="panel-title">Classement Race</h3>
                </a>
            </div>

            <div class="panel-body">
                <div class="table">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Participant</th>
                                <th>Points</th>
                                <th>Tournois</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in race_ranking %}
                                <tr>
                                    <td>{{ loop.index }}</td>
                                    <td><a href= '{{ url_for("main.view_user", user_id = user.id, _external = True) }}'>{{ user.username }}</td>
                                    <td>
                                        {% if user.year_to_date_points is none %}
                                            0
                                        {% else %}
                                            {{ user.year_to_date_points }}
                                        {% endif %}
                                    </td>
                                    <td>
                                        {{ user.year_to_date_number_tournaments }}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-8">
        {% if current_tournament %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="{{ url_for('tournament.view_tournament', tournament_id = current_tournament.id) }}">
                    <h3 class="panel-title">
                        Tournoi en cours : {{ current_tournament.name }}
                    </h3>
                </a>
            </div>

            <div class="panel-body">
                {% if current_tournament.is_open_to_registration() %}
                    <p>Date limite d'inscription : {{ current_tournament.started_at }}</p>
                {% endif %}

                {% if current_tournament.participants.first() %}
                    <div class="table">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Participant</th>
                                    <th>Score / {{ current_tournament.current_maximal_score }}</th>
                                    <th>Coefficient de risque</th>
                                    {% if current_tournament.is_finished() %}
                                        <th>Points ATP</th>
                                    {% endif %}
                                    <th>Tableau</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for participant in current_tournament.participants_sorted() %}
                                    {% if not current_tournament.are_draws_private() %}
                                        <tr>
                                            <td>{{ loop.index }}</td>
                                            <th>
                                                <a href= '{{ url_for("main.view_user", user_id = participant.user.id, _external = True) }}'>
                                                {{ participant.user.username }}</a>
                                            </th>
                                            <th>{{ participant.score }}</th>
                                            <td>{{ participant.risk_coefficient | int }}</td>
                                            {% if current_tournament.is_finished() %}
                                                <td>{{ participant.points }}</td>
                                            {% endif %}
                                            <td>
                                                <a href= '{{ url_for("tournament.view_participant_draw", tournament_id = current_tournament.id, participant_id = participant.id, _external = True) }}'>
                                                Voir</a>
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <th>-</th>
                                            <th>
                                                <a href= '{{ url_for("main.view_user", user_id = participant.user.id, _external = True) }}'>
                                                {{ participant.user.username }}</a>
                                            </th>
                                            <td>-</td>
                                            <td>-</td>
                                            <td>-</td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    Aucun participant à ce tournoi pour le moment
                {% endif %}

            </div>
        </div>
        {% else %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="{{ url_for('tournament.view_tournaments') }}">
                        <h3 class="panel-title">Tournois passés</h3>
                    </a>
                </div>

                <div class="panel-body">
                    <div class="table">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Tournoi</th>
                                    <th>Participants</th>
                                    <th>Vainqueur</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for tournament in tournaments %}
                                    <tr>
                                        <td><a href="{{ url_for('tournament.view_tournament', tournament_id = tournament.id) }}">{{ tournament.name }}</a></td>
                                        <td>{{ tournament.participants.all() | length }}</td>

                                        {% with winner = tournament.participants_sorted().first() %}
                                            {% if tournament.is_finished() and winner %}
                                                <td><a href="{{ url_for('main.view_user', user_id = winner.user.id) }}">{{ winner.user.username }}</a></td>
                                            {% else %}
                                                <td></td>
                                            {% endif %}
                                        {% endwith %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        {% endif %}

    </div>
</div>

{% endblock %}

app/templates/main/view_users.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block content %}

<main>


<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Liste des utilisateurs</h3>
    </div>

    <div class="panel-body">
        <div class="table">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Pseudo</th>
                        {% if current_user.is_administrator() %}<th>Email</th>{% endif %}
                        <th>Role</th>
                        <th>Compte confirmé</th>
                        <th>Ancien compte</th>
                        <th>Tournois joués</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in pagination.items %}
                        <tr>
                            <td>{{ page_start_index + loop.index }}</td>
                            <td><a href="{{ url_for('main.view_user', user_id = user.id) }}">{{ user.username }}</a></td>
                            {% if current_user.is_administrator() %}<td>{{ user.email }}</td>{% endif %}
                            <td>{{ user.role }}</td>
                            <td>{% if user.confirmed %}Oui{% else %}Non{% endif %}</td>
                            <td>{% if user.is_old_account %}Oui{% else %}Non{% endif %}</td>
                            <td>{{ user.participants.count() }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        {{ macros.pagination_widget(pagination, '.view_users') }}

    </div>
</div>



{% endblock %}