app/tournament/forms/__init__.py
from .create_tournament import CreateTournamentForm
from .edit_tournament import EditTournamentForm
from .fill_tournament_draw import FillTournamentDrawForm
from .tournament_draw import PlayerTournamentDrawForm, CreateTournamentDrawForm
from .tournament_player_stats import TournamentPlayerStatsForm, TournamentPlayerAlphabeticStatsForm

app/tournament/forms/create_tournament.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, DateTimeField
from wtforms.validators import DataRequired, InputRequired, Optional

from ...lang import WORDINGS


class CreateTournamentForm(FlaskForm):
    name = StringField(
        WORDINGS.TOURNAMENT.NAME,
        validators=[
            DataRequired(message=WORDINGS.COMMON.MISSING_FIELD)
        ]
    )
    tournament_topic_url = StringField(
        WORDINGS.TOURNAMENT.URL_JVC,
        validators=[
            Optional()
        ]
    )
    jeudelorgue_topic_url = StringField(
        WORDINGS.TOURNAMENT.URL_JDL_JVC,
        validators=[
            Optional()
        ]
    )
    category = SelectField(
        WORDINGS.TOURNAMENT.CATEGORY,
        coerce=int
    )
    surface = SelectField(
        WORDINGS.TOURNAMENT.SURFACE,
        coerce=int
    )
    start_date = DateTimeField(
        WORDINGS.TOURNAMENT.START_DATE,
        format="%d/%m/%Y %H:%M",
        validators=[
            InputRequired(message=WORDINGS.COMMON.MISSING_FIELD)
        ]
    ) 

app/tournament/forms/fill_tournament_draw.py
from flask_wtf import FlaskForm
from wtforms import StringField


class FillTournamentDrawForm(FlaskForm):
    forecast = StringField("forecast") 

app/tournament/__init__.py
from flask import Blueprint

bp = Blueprint('tournament', __name__)

from . import views
from .domain import get_tournament

app/tournament/domain/__init__.py
from .compute_risk_coefficient_by_participant import compute_risk_coefficient_by_participant
from .create_tournament import create_tournament
from .create_tournament_draw import create_tournament_draw
from .edit_tournament import edit_tournament
from .edit_tournament_draw import edit_tournament_draw
from .get_categories import get_categories
from .get_current_tournament import get_current_tournament
from .get_surfaces import get_surfaces
from .get_tournament import get_tournament

app/tournament/domain/entities/__init__.py
from . TournamentPlayer import TournamentPlayer

app/tournament/views/__init__.py
from .close_registrations import close_registrations
from .close_tournament import close_tournament
from .create_tournament import create_tournament
from .create_tournament_draw import create_tournament_draw
from .current_tournament import current_tournament
from .delete_tournament import delete_tournament
from .edit_my_draw import edit_my_draw
from .edit_tournament import edit_tournament
from .edit_tournament_draw import edit_tournament_draw
from .fill_my_draw import fill_my_draw
from .open_registrations import open_registrations
from .overall_forecasts_stats import overall_forecasts_stats
from .raw_tournament_ranking import raw_tournament_ranking
from .register import register
from .scenario_simulator import scenario_simulator
from .tournament_player_stats import tournament_player_stats
from .update_tournament_draw import update_tournament_draw
from .view_participant_draw import view_participant_draw
from .view_participant_draw_last16 import view_participant_draw_last16
from .view_tournament import view_tournament
from .view_tournament_draw import view_tournament_draw
from .view_tournament_draw_last16 import view_tournament_draw_last16
from .view_tournaments import view_tournaments

app/tournament/views/close_registrations.py
from .. import bp
from .. import domain
from .. import routing
from ...decorators import manager_required
from ...lang import WORDINGS
from ...models import db, TournamentStatus
from ...utils import display_info_toast


@bp.route("/<tournament_id>/close_registrations")
@manager_required
def close_registrations(tournament_id):
    tournament = domain.get_tournament(tournament_id)
    tournament.status = TournamentStatus.ONGOING
    db.session.add(tournament)
    db.session.commit()

    for participant in tournament.participants:
        if not participant.has_filled_draw():
            db.session.delete(participant)
    db.session.commit()

    risk_coefficient_by_participant = domain.compute_risk_coefficient_by_participant(tournament)
    for participant in tournament.participants:
        participant.risk_coefficient = risk_coefficient_by_participant[participant.id]
        db.session.add(participant)
    db.session.commit()

    display_info_toast(WORDINGS.TOURNAMENT.REGISTRATION_CLOSED)
    return routing.redirect_to_view_tournament(tournament.id) 

app/tournament/views/close_tournament.py
import datetime

from .. import bp
from .. import domain
from .. import routing
from ...decorators import manager_required
from ...lang import WORDINGS
from ...models import db, TournamentStatus
from ...ranking import domain as ranking_domain
from ...utils import display_info_toast


@bp.route("/<tournament_id>/close_tournament")
@manager_required
def close_tournament(tournament_id):
    tournament = domain.get_tournament(tournament_id)
    tournament.status = TournamentStatus.FINISHED
    tournament.ended_at = datetime.datetime.now()
    db.session.add(tournament)
    db.session.commit()

    scores = tournament.distribute_points()
    for rank, participant in enumerate(tournament.participants_sorted()):
        participant.points = scores[participant]
        participant.user.annual_points = participant.user.get_annual_points()
        participant.user.year_to_date_points = participant.user.get_year_to_date_points()
        participant.ranking = rank + 1
        db.session.add(participant)
    db.session.commit()

    ranking_domain.compute_historical_rankings(tournament)

    display_info_toast(WORDINGS.TOURNAMENT.TOURNAMENT_CLOSED)
    return routing.redirect_to_view_tournament(tournament.id) 

app/tournament/views/create_tournament.py
from flask import render_template, request

from .. import bp
from .. import domain
from .. import routing
from ..forms import CreateTournamentForm
from ...decorators import manager_required
from ...lang import WORDINGS
from ...utils import display_info_toast


@bp.route("/create", methods=["GET", "POST"])
@manager_required
def create_tournament():
    form = CreateTournamentForm(request.form)
    form.category.choices = domain.get_categories()
    form.surface.choices = domain.get_surfaces()

    if form.validate_on_submit():
        tournament = domain.create_tournament(form)
        display_info_toast(WORDINGS.TOURNAMENT.TOURNAMENT_CREATED.format(form.name.data))
        return routing.redirect_to_view_tournament(tournament.id)
    else:
        return render_template(
            "tournament/create_tournament.html",
            title=WORDINGS.TOURNAMENT.CREATE_TOURNAMENT,
            form=form
        ) 

app/tournament/views/create_tournament_draw.py
from flask import render_template, request

from .. import bp
from .. import domain
from .. import routing
from ..forms import CreateTournamentDrawForm
from ...decorators import manager_required
from ...lang import WORDINGS
from ...models import Player
from ...utils import display_info_toast


@bp.route("/<tournament_id>/draw/create", methods=["GET", "POST"])
@manager_required
def create_tournament_draw(tournament_id):
    tournament = domain.get_tournament(tournament_id)
    title = "{} - Créer le tableau".format(tournament.name)

    matches = tournament.get_matches_first_round()

    if not request.form:
        form = CreateTournamentDrawForm()

        for _ in matches:
            form.player.append_entry()

    else:
        form = CreateTournamentDrawForm(request.form)

    player_names = [(-1, WORDINGS.PLAYER.CHOOSE_PLAYER)] + Player.get_all_players()

    for p in form.player:
        p.player1_name.choices = player_names
        p.player2_name.choices = player_names

    if form.validate_on_submit():
        domain.create_tournament_draw(tournament, matches, form)

        display_info_toast(WORDINGS.TOURNAMENT.TOURNAMENT_DRAW_CREATED.format(tournament.name))
        return routing.redirect_to_view_tournament(tournament_id)
    else:
        return render_template(
            "tournament/create_tournament_draw.html",
            title=title,
            form=form,
            tournament=tournament,
            surface=tournament.surface.class_name
        ) 

app/tournament/views/current_tournament.py
from flask_login import login_required

from .. import bp
from .. import domain
from .. import routing


@bp.route("/current")
@login_required
def current_tournament():
    tournament = domain.get_current_tournament()
    if tournament:
        return routing.redirect_to_view_tournament(tournament.id)
    else:
        return routing.redirect_to_view_tournaments() 

app/tournament/views/delete_tournament.py
import datetime

from .. import bp
from .. import domain
from .. import routing
from ...decorators import manager_required
from ...lang import WORDINGS
from ...models import db
from ...utils import display_info_toast


@bp.route("/<tournament_id>/delete")
@manager_required
def delete_tournament(tournament_id):
    tournament = domain.get_tournament(tournament_id)
    tournament.deleted_at = datetime.datetime.now()
    db.session.add(tournament)
    db.session.commit()
    display_info_toast(WORDINGS.TOURNAMENT.TOURNAMENT_DELETED.format(tournament.name))
    return routing.redirect_to_view_tournaments() 

app/tournament/views/edit_my_draw.py
import json

from flask import render_template
from flask_login import login_required, current_user

from .. import bp
from .. import domain
from .. import routing
from ..forms import FillTournamentDrawForm
from ...lang import WORDINGS
from ...models import db, Participant
from ...utils import display_success_toast, display_warning_toast


@bp.route("/<tournament_id>/draw/<participant_id>/edit", methods=["GET", "POST"])
@login_required
def edit_my_draw(tournament_id, participant_id):
    tournament = domain.get_tournament(tournament_id)
    participant = Participant.query.get_or_404(participant_id)
    if participant.user_id != current_user.id:
        return routing.redirect_to_view_tournament(tournament_id)

    if not tournament.is_open_to_registration():
        return routing.redirect_to_view_tournament(tournament_id)

    title = "{} - Modifier mon tableau".format(tournament.name)
    form = FillTournamentDrawForm()

    if form.validate_on_submit():
        forecasts = json.loads(form.forecast.data)
        current_forecasts = participant.forecasts

        for current_forecast in current_forecasts:
            winner_id = forecasts[str(current_forecast.match_id)]
            if winner_id == "None":
                current_forecast.winner_id = None
            else:
                current_forecast.winner_id = winner_id
            db.session.add(current_forecast)
        db.session.commit()

        if participant.has_completely_filled_draw():
            display_success_toast(WORDINGS.TOURNAMENT.DRAW_FILLED_COMPLETELY)
        else:
            display_warning_toast(WORDINGS.TOURNAMENT.DRAW_NOT_FILLED_COMPLETELY)
        return routing.redirect_to_view_tournament(tournament_id)

    else:
        return render_template(
            "tournament/edit_my_draw.html",
            title=title,
            tournament=tournament,
            participant=participant,
            form=form,
            surface=tournament.surface.class_name
        ) 

app/tournament/views/edit_tournament.py
from flask import render_template, request

from .. import bp
from .. import domain
from .. import routing
from ..forms import EditTournamentForm
from ...decorators import manager_required
from ...lang import WORDINGS
from ...utils import display_info_toast


@bp.route("/<tournament_id>/edit", methods=["GET", "POST"])
@manager_required
def edit_tournament(tournament_id):
    tournament = domain.get_tournament(tournament_id)
    title = tournament.name
    form = EditTournamentForm(request.form)

    form.category.choices = domain.get_categories()
    form.surface.choices = domain.get_surfaces()

    if request.method == "GET":
        form.name.data = tournament.name
        form.category.data = tournament.category_id
        form.surface.data = tournament.surface_id
        form.start_date.data = tournament.started_at
        form.tournament_topic_url.data = tournament.tournament_topic_url
        form.jeudelorgue_topic_url.data = tournament.jeudelorgue_topic_url
    if form.validate_on_submit():
        domain.edit_tournament(tournament, form)
        display_info_toast(WORDINGS.TOURNAMENT.TOURNAMENT_UPDATED.format(form.name.data))
        return routing.redirect_to_edit_tournament(tournament_id)
    else:
        return render_template(
            "tournament/edit_tournament.html",
            title=title,
            form=form,
            tournament=tournament,
            surface=tournament.surface.class_name
        ) 

app/tournament/views/edit_tournament_draw.py
from flask import render_template, request

from .. import bp
from .. import domain
from .. import routing
from ..forms import CreateTournamentDrawForm
from ...decorators import manager_required
from ...lang import WORDINGS
from ...models import Player
from ...utils import display_info_toast


@bp.route("/<tournament_id>/draw/edit", methods=["GET", "POST"])
@manager_required
def edit_tournament_draw(tournament_id):
    tournament = domain.get_tournament(tournament_id)
    matches = tournament.get_matches_first_round()

    if not request.form:
        form = CreateTournamentDrawForm()

        for _ in matches:
            form.player.append_entry()

    else:
        form = CreateTournamentDrawForm(request.form)

    player_names = [(-1, WORDINGS.PLAYER.CHOOSE_PLAYER)] + Player.get_all_players()

    for p in form.player:
        p.player1_name.choices = player_names
        p.player2_name.choices = player_names

    if request.method == "GET":
        for p, match in zip(form.player, matches):
            if match.tournament_player1:
                if match.tournament_player1.player:
                    p.player1_name.data = match.tournament_player1.player.id
                p.player1_status.data = match.tournament_player1.status
                p.player1_seed.data = match.tournament_player1.seed
            if match.tournament_player2:
                if match.tournament_player2.player:
                    p.player2_name.data = match.tournament_player2.player.id
                p.player2_status.data = match.tournament_player2.status
                p.player2_seed.data = match.tournament_player2.seed

    if form.validate_on_submit():
        domain.edit_tournament_draw(tournament, matches, form)

        display_info_toast(WORDINGS.TOURNAMENT.TOURNAMENT_DRAW_UPDATED.format(tournament.name))
        return routing.redirect_to_view_tournament(tournament_id)
    else:
        return render_template(
            "tournament/edit_tournament_draw.html",
            title=WORDINGS.TOURNAMENT.CREATE_TOURNAMENT_DRAW,
            form=form,
            tournament=tournament,
            surface=tournament.surface.class_name
        ) 

app/tournament/views/fill_my_draw.py
import json

from flask import render_template
from flask_login import login_required, current_user

from .. import bp
from .. import domain
from .. import routing
from ..forms import FillTournamentDrawForm
from ...lang import WORDINGS
from ...models import db, Participant, Forecast
from ...utils import display_success_toast, display_warning_toast


@bp.route("/<tournament_id>/draw/<participant_id>/fill", methods=["GET", "POST"])
@login_required
def fill_my_draw(tournament_id, participant_id):
    tournament = domain.get_tournament(tournament_id)
    participant = Participant.query.get_or_404(participant_id)
    if participant.user_id != current_user.id:
        return routing.redirect_to_view_tournament(tournament_id)

    if not tournament.is_open_to_registration():
        return routing.redirect_to_view_tournament(tournament_id)

    title = WORDINGS.TOURNAMENT.FILL_MY_DRAW.format(tournament.name)

    if participant.has_filled_draw():
        return routing.redirect_to_edit_my_draw(tournament_id, participant_id)

    form = FillTournamentDrawForm()

    if form.validate_on_submit():
        forecasts = json.loads(form.forecast.data)
        for match_id, tournament_player_id in forecasts.items():
            if tournament_player_id != "None":
                forecast = Forecast(
                    match_id=match_id,
                    winner_id=tournament_player_id,
                    participant_id=participant_id
                )
            else:
                forecast = Forecast(
                    match_id=match_id,
                    winner_id=None,
                    participant_id=participant_id
                )
            db.session.add(forecast)
        db.session.commit()

        if participant.has_completely_filled_draw():
            display_success_toast(WORDINGS.TOURNAMENT.DRAW_FILLED_COMPLETELY)
        else:
            display_warning_toast(WORDINGS.TOURNAMENT.DRAW_NOT_FILLED_COMPLETELY)
        return routing.redirect_to_view_tournament(tournament_id)

    else:
        return render_template(
            "tournament/fill_my_draw.html",
            title=title,
            tournament=tournament,
            participant=participant,
            form=form,
            surface=tournament.surface.class_name
        ) 

app/templates/tournament/create_tournament_draw.html
{% extends "base.html" %}

{% block styles %}

{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/{}.css'.format(tournament.surface.class_name)) | autoversion }}">
{% endblock %}


{% block content %}

<div class="panel panel-default">

    <div class="panel-heading">
        <h3 class="panel-title">
            <a href="{{ url_for('.view_tournament', tournament_id=tournament.id) }}">
            {{ tournament.name }}</a>
             - Créer le tableau
        </h3>
    </div>

    <form action="{{ url_for('tournament.create_tournament_draw', tournament_id=tournament.id) }}"
          class="form-horizontal" method="POST">
        {{ form.hidden_tag() }}

        <div class="panel-body">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">

                    <div class="btn-group" role="group">
                        <a class="btn btn-success"
                               href="{{ url_for('player.create_player') }}"
                               target="_blank">
                            <span class="fa fa-pencil"></span>
                                Créer un nouveau joueur
                        </a>
                    </div>

                    <div class="table">
                        <table class="table table-striped table-bordered table-condensed">
                            <colgroup>
                                <col span="1" style="width: 5%;">
                                <col span="1" style="width: 65%;">
                                <col span="1" style="width: 15%;">
                                <col span="1" style="width: 15%;">
                            </colgroup>
                            <thead class="thead-default">
                            <tr>
                                <th>#</th>
                                <th>Joueur</th>
                                <th>Statut</th>
                                <th>Tête de série</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for match in form.player %}
                            <tr>
                                <th scope="row">{{ 2 * loop.index - 1}}</th>
                                <td class="form-group {% if match.player1_name.errors %} has-error {% endif %}">{{
                                    match.player1_name(class="form-control") }}
                                </td>
                                <td class="form-group {% if match.player1_status.errors %} has-error {% endif %}">{{
                                    match.player1_status(class="form-control") }}
                                </td>
                                <td class="form-group {% if match.player1_seed.errors %} has-error {% endif %}">{{
                                    match.player1_seed(class="form-control") }}
                                </td>

                            </tr>
                            <tr>
                                <th scope="row">{{ 2 * loop.index }}</th>
                                <td class="form-group {% if match.player2_name.errors %} has-error {% endif %}">{{
                                    match.player2_name(class="form-control") }}
                                </td>
                                <td class="form-group {% if match.player2_status.errors %} has-error {% endif %}">{{
                                    match.player2_status(class="form-control") }}
                                </td>
                                <td class="form-group {% if match.player2_seed.errors %} has-error {% endif %}">{{
                                    match.player2_seed(class="form-control") }}
                                </td>

                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <div class="form-group">
                        <button class="btn btn-success" type="submit">Valider</button>
                    </div>
                </div>

            </div>
        </div>
    </form>
</div>

{% endblock %}

app/templates/tournament/edit_my_draw.html
{% extends "base.html" %}

{% block styles %}
{{ super() }}

<link rel="stylesheet" href="{{ url_for('static', filename='css/draw.css') | autoversion }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/{}.css'.format(tournament.surface.class_name)) | autoversion }}">

{% endblock %}


{% block content %}

<div class="panel panel-default">

    <div class="panel-heading">
        <h3 class="panel-title">
            <a href="{{ url_for('.view_tournament', tournament_id=tournament.id) }}">
            {{ tournament.name }}</a>
             - Modifier mon tableau
        </h3>
    </div>

    <div class="panel-body">
        <div class="alert alert-info">
            <p>Cliquez sur le nom d'un joueur pour le faire avancer au tour suivant.</p>
            <p>Vous pouvez remplir seulement une partie du tableau, valider, et revenir plus tard pour le compléter.</p>
            <p>Ctrl + clic pour effacer le contenu d'une case du tableau.</p>
        </div>

        <div class="row">
            <div class="col-md-12">
                <form action="{{ url_for('tournament.edit_my_draw', tournament_id=tournament.id, participant_id=participant.id) }}" method="POST">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        <button class="btn btn-success" type="submit">Valider</button>
                    </div>
                    <div class="form-group">
                        <div>
                            {{form.forecast(class="form-control", type = "hidden")}}
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="main">
            <div id="round-names" class="draw">
                {% for round in tournament.get_matches_by_round() %}
                    <div class="round">
                        <div class="round-name">
                            {{ tournament.get_round_names()[loop.index - 1] }}
                        </div>
                    </div>
                {% endfor %}
                    <div class="round">
                        <div class="round-name">
                            V
                        </div>
                    </div>
            </div>

            <div id="tournament" class="draw">

                {% with matches = tournament.get_matches_first_round() %}
                    <div class="round">
                        <div class="spacer">
                            &nbsp;
                        </div>

                        {% for match in matches %}
                            <div id="player-{{ match.position }}-0"
                                class="game game-player match first-round"
                                tournament_player_id="{{ match.tournament_player1_id }}"
                                match_position_id="{{ match.position }}"
                                match_id="{{ match.id }}"
                                {% if not match.tournament_player1.is_bye() %}
                                    onclick="fill_next_round(event, {{ match.position }}, 0)"
                                {% endif %}>
                                {% if match.tournament_player1_id %}
                                    {{ match.tournament_player1.get_full_name() | truncate(35) }}
                                {% else %}
                                    &nbsp;
                                {% endif %}
                            </div>

                            <div class="game game-spacer">
                                &nbsp;
                            </div>

                            <div id="player-{{ match.position }}-1"
                                class="game game-player match first-round"
                                tournament_player_id="{{ match.tournament_player2_id }}"
                                match_position_id="{{ match.position }}"
                                match_id="{{ match.id }}"
                                {% if not match.tournament_player2.is_bye() %}
                                    onclick="fill_next_round(event, {{ match.position }}, 1)"
                                {% endif %}>
                                {% if match.tournament_player2_id %}
                                    {{ match.tournament_player2.get_full_name() | truncate(35) }}
                                {% else %}
                                    &nbsp;
                                {% endif %}
                            </div>

                            <div class="spacer">
                                &nbsp;
                            </div>

                        {% endfor %}

                    </div>
                {% endwith %}


                {% for round in tournament.get_matches_by_round() %}

                    {% if loop.index < loop.length %}

                        <div class="round">
                            <div class="spacer">
                                &nbsp;
                            </div>

                            {% for match in round["matches"] %}

                                {% with next_match = match.get_next_match() %}

                                    {% with forecast = match.get_forecast(participant.id) %}
                                        {% if forecast.winner %}

                                            <div id="player-{{ next_match.position }}-{{ loop.cycle(0, 1) }}"
                                                class="game game-player match"
                                                tournament_player_id="{{ forecast.winner_id }}"
                                                match_position_id="{{ next_match.position }}"
                                                match_id="{{ next_match.id }}"
                                                onclick="fill_next_round(event, {{ next_match.position }}, {{ loop.cycle(0, 1) }})">
                                                    {{ forecast.winner.get_full_name() | truncate(35) }}
                                            </div>

                                        {% else %}

                                            <div id="player-{{ next_match.position }}-{{ loop.cycle(0, 1) }}"
                                                class="game game-player match"
                                                tournament_player_id="None"
                                                match_position_id="{{ next_match.position }}"
                                                match_id="{{ next_match.id }}"
                                                onclick="fill_next_round(event, {{ next_match.position }}, {{ loop.cycle(0, 1) }})">
                                                &nbsp;
                                            </div>

                                        {% endif %}

                                        <div class="{{ loop.cycle('game game-spacer', 'spacer') }}">
                                            &nbsp;
                                        </div>

                                    {% endwith %}
                                {% endwith %}
                            {% endfor %}

                        </div>
                    {% else %}

                        {% with match = round["matches"][0] %}
                            {% with forecast = match.get_forecast(participant.id) %}
                                <div class="round last-round">
                                    <div id="player-0-1"
                                        class="game game-player"
                                        tournament_player_id="{{ forecast.winner_id }}"
                                        match_position_id="0"
                                        onclick="fill_next_round(event, 0, 1)">
                                        {% if forecast.winner %}
                                            {{ forecast.winner.get_full_name() | truncate(35) }}
                                        {% else %}
                                            &nbsp;
                                        {% endif %}
                                    </div>
                                </div>
                            {% endwith %}
                        {% endwith %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>



{% endblock %}

{% block extrajs %}
    <script src="{{ url_for('static', filename='js/draw.js') | autoversion }}"></script>
{% endblock %}

app/templates/tournament/raw_tournament_ranking.html
:fete: Classement après ... :fete:
<br>
<br>

{% for participant in tournament.participants_sorted() %}
    {{ loop.index }}. {{ participant.user.username }} ({{ participant.score }}/{{ tournament.current_maximal_score }})<br>
{% endfor %}