app/main/views/faq.py
from flask import render_template

from .. import bp
from ...lang import WORDINGS


@bp.route("/faq")
def faq():
    return render_template(
        "main/faq.html",
        title=WORDINGS.MAIN.FAQ
    ) 

app/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, redirect, request, session, flash, url_for
from flask_login import login_user, logout_user, login_required, current_user
from .models import db, bcrypt
from .models import User
from .forms import LoginForm, SignupForm
from .texts import ACCOUNT_CREATED, LOGIN_SUCCESSFUL
from .texts import INCORRECT_CREDENTIALS, USERNAME_ALREADY_TAKEN, EMAIL_ALREADY_TAKEN


bp = Blueprint("main", __name__)


@bp.route("/")
@bp.route("/index")
def index():
    title = "Accueil"
    return render_template("index.html", title = title)


@bp.route("/signup", methods = ["GET", "POST"])
def signup():
    title = "Inscription"
    form = SignupForm(request.form)

    if form.validate_on_submit():
        user_exist = User.query.filter_by(username = form.username.data).first()
        email_exist = User.query.filter_by(email = form.email.data).first()
        if user_exist:
            form.username.errors.append(USERNAME_ALREADY_TAKEN)
        if email_exist:
            form.email.errors.append(EMAIL_ALREADY_TAKEN)
        if user_exist or email_exist:
            return render_template("signup.html", form = form, title = title)
        else:
            user = User(username = form.username.data,
                        email = form.email.data,
                        password = form.password.data)
            db.session.add(user)
            db.session.commit()
            flash(ACCOUNT_CREATED)
            session.pop("signed", None)
            session.pop("username", None)
            logout_user()
            return redirect(url_for("main.login"))
    else:
        return render_template("signup.html", form = form, title = title)


@bp.route("/login", methods = ["GET", "POST"])
def login():
    form = LoginForm()
    title = "Connexion"

    # Redirect user to homepage if they are already authenticated
    if current_user is not None and current_user.is_authenticated:
        return redirect(url_for("main.index"))

    # If form was submitted via a POST request
    if form.validate_on_submit():
        user = User.query.filter_by(username = form.username.data).first()

        # If the credentials are incorrect, render the login page with an error message
        if user is None:
            form.username.errors.append(INCORRECT_CREDENTIALS)
            form.password.errors.append("")
            return render_template("login.html", form = form, title = title)

        is_password_correct = bcrypt.check_password_hash(user.password, form.password.data)
        if not is_password_correct:
            form.username.errors.append(INCORRECT_CREDENTIALS)
            form.password.errors.append("")
            return render_template("login.html", form = form, title = title)

        # Otherwise log the user in
        login_user(user, remember = form.remember_me.data)
        session["signed"] = True
        session["username"] = user.username
        flash(LOGIN_SUCCESSFUL)

        # Redirect the user to the page he initially wanted to access
        if session.get("next"):
            next_page = session.get("next")
            session.pop("next")
            return redirect(next_page)
        else:
            return redirect(url_for("main.index"))

    session["next"] = request.args.get("next")
    return render_template("login.html", form = form, title = title)


@bp.route("/logout")
@login_required
def logout():
    session.pop("signed", None)
    session.pop("username", None)
    logout_user()
    return redirect(url_for("main.index"))

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}

<ul class="pagination">
    <li {% if not pagination.has_prev %} class="disabled" {% endif %}>
    <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page = pagination.page - 1, **kwargs) }}{% else %}#{% endif %}">&laquo;</a>
    </li>
    {% for p in pagination.iter_pages() %}
    {% if p %}
    {% if p == pagination.page %}
    <li class="active">
        <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
    </li>
    {% else %}
    <li>
        <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
    </li>
    {% endif %}
    {% else %}
    <li class="disabled"><a href="#">&hellip;</a></li>
    {% endif %}
    {% endfor %}
    <li {% if not pagination.has_next %} class="disabled" {% endif %}>
    <a href="{% if pagination.has_next %}{{ url_for(endpoint, page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
        &raquo;
    </a>
    </li>
</ul>
{% endmacro %}

{% macro confirmation_modal() %}
<div class="modal fade" id="formConfirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Fermer</span></button>
        <h4 class="modal-title" id="frm_title">Confirmer</h4>
      </div>
      <div class="modal-body" id="frm_body"></div>
      <div class="modal-footer">
        <button style='margin-left:10px;' type="button" class="btn btn-success col-sm-2 pull-right" id="frm_submit">Oui</button>
        <button type="button" class="btn btn-danger col-sm-2 pull-right" data-dismiss="modal" id="frm_cancel">Non</button>
      </div>
    </div>
  </div>
</div>
{% endmacro %}

app/templates/base.html
<!DOCTYPE html>
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block head %}
{{ super() }}

<title>
    {% block title %}Le jeu de L-orgue{% if title %} - {{ title }}{% endif %}{% endblock %}
</title>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='images/tennis_ball.ico') }}">

{% endblock %}

{% block styles %}

{{ super() }}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/global.css') | autoversion }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css') | autoversion }}">

{% endblock %}


{% block body %}

{% block navbar %}
<nav class="navbar navbar-default navbar-static-top navbar-fixed-top">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Le jeu de L-orgue</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
                {% if current_user.is_authenticated %}
                    <li>
                        <a href="{{ url_for('tournament.view_tournaments') }}">
                            <span class="fa fa-trophy" aria-hidden="true"></span>
                            Tournois
                        </a>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="fa fa-list-ol" aria-hidden="true"></span>
                            Classements <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{{ url_for('ranking.race_ranking') }}">
                                    <span class="fa fa-flag-checkered" aria-hidden="true"></span>
                                    Race
                                </a>
                            </li>
                            <li>
                                <a href="{{ url_for('ranking.annual_ranking') }}">
                                    <span class="fa fa-calendar" aria-hidden="true"></span>
                                    Annuel
                                </a>
                            </li>
                            <li>
                                <a href="{{ url_for('ranking.all_rankings') }}">
                                    <span class="fa fa-list" aria-hidden="true"></span>
                                    Historique
                                </a>
                            </li>
                        </ul>
                    </li>
                {% endif %}

                <li>
                    <a href="{{ url_for('main.faq') }}">
                        <span class="fa fa-question-circle" aria-hidden="true"></span>
                        FAQ
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('main.contact') }}">
                        <span class="fa fa-pencil" aria-hidden="true"></span>
                        Contact
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_manager() %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="fa fa-lock" aria-hidden="true"></span>
                        Admin <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{{ url_for('tournament.create_tournament') }}">
                                <span class="fa fa-trophy" aria-hidden="true"></span>
                                Créer un tournoi
                            </a>
                        </li>
                        <li>
                            <a href="{{ url_for('tournament_category.view_categories') }}">
                                <span class="fa fa-list" aria-hidden="true"></span>
                                Catégories de tournois
                            </a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="{{ url_for('main.view_users') }}">
                                <span class="fa fa-user" aria-hidden="true"></span>
                                Utilisateurs
                            </a>
                        </li>
                        <li>
                            <a href="{{ url_for('main.view_validated_users') }}">
                                <span class="fa fa-user" aria-hidden="true"></span>
                                Utilisateurs validés
                            </a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="{{ url_for('player.view_players') }}">
                                <span class="fa fa-list" aria-hidden="true"></span>
                                Joueurs ATP
                            </a>
                        </li>
                    </ul>
                </li>
                {% endif %}

                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="fa fa-user" aria-hidden="true"></span>
                        {{ current_user.username}} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{{ url_for('main.view_user', user_id=current_user.id) }}">
                                <span class="fa fa-user" aria-hidden="true"></span>
                                Mon profil
                            </a>
                        </li>
                        <li>
                            <a href="{{ url_for('auth.change_password') }}">
                                <span class="fa fa-lock" aria-hidden="true"></span>
                                Modification du mot de passe
                            </a>
                        </li>
                        <li>
                            <a href="{{ url_for('auth.logout') }}">
                                <span class="fa fa-sign-out" aria-hidden="true"></span>
                                Déconnexion
                            </a>
                        </li>
                    </ul>
                </li>
                {% else %}
                <li>
                    <a href="/signup">
                        <span class="fa fa-user-plus" aria-hidden="true"></span>
                        Inscription
                    </a>
                </li>
                <li>
                    <a href="/login">
                        <span class="fa fa-sign-in" aria-hidden="true"></span>
                        Connexion
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>
{% endblock %}


<div class="container-fluid">
    {% for category, message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ category }} alert-dismissible">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor %}
    {% block content %}{% endblock %}
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

{% block extrajs %}{% endblock %}

{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">

                <div class="panel-heading">
                    <h3 class="panel-title"><strong>Connexion</strong></h3>
                </div>

                <form action="{{ url_for('main.login') }}" class="form-horizontal" method="POST">
                    {{ form.hidden_tag() }}

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">

                                <div class="form-group {% if form.username.errors %} has-error {% endif %}">
                                    {{form.username.label()}}
                                    <div>
                                        {{form.username(placeholder="Pseudo", class="form-control")}}
                                    </div>
                                    <p class="help-block">
                                        {{ form.username.errors[0] }}
                                </div>

                                <div class="form-group {% if form.password.errors %} has-error {% endif %}">
                                    {{form.password.label()}}
                                    <div>
                                        {{ form.password(placeholder="Min. 6 Characters", class="form-control") }}
                                    </div>
                                    <p class="help-block">
                                        {{ form.password.errors[0] }}
                                </div>

                                <div class="form-group {% if form.remember_me .errors %} has-error {% endif %}">
                                    <div class="checkbox">
                                        <label>{{ form.remember_me }} {{ form.remember_me.label}}</label>
                                    </div>
                                    <p class="help-block">
                                        {{ form.remember_me.errors[0] }}
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-success" type="submit">Se connecter</button>
                                    <span class="pull-right">
                                        Pas encore inscrit ?
                                        <a href="{{ url_for('main.signup') }}">Créer un compte</a>
                                    </span>
                                </div>

                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

app/templates/signup.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">

                <div class="panel-heading">
                    <h3 class="panel-title"><strong>Inscription</strong></h3>
                </div>

                <form action="{{ url_for('main.signup') }}" class="form-horizontal" method="POST">
                    {{ form.hidden_tag() }}

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">

                                <div class="form-group {% if form.email.errors %} has-error {% endif %}">
                                    {{form.email.label()}}
                                    <div>
                                        {{form.email(class="form-control")}}
                                    </div>
                                    <p class="help-block">
                                        {{ form.email.errors[0] }}
                                </div>

                                <div class="form-group {% if form.username.errors %} has-error {% endif %}">
                                    {{form.username.label()}}
                                    <div>
                                        {{form.username(class="form-control")}}
                                    </div>
                                    <p class="help-block">
                                        {{ form.username.errors[0] }}
                                </div>

                                <div class="form-group {% if form.password.errors %} has-error {% endif %}">
                                    {{form.password.label()}}
                                    <div>
                                        {{ form.password(placeholder="Min. 6 caractères", class="form-control") }}
                                    </div>
                                    <p class="help-block">
                                        {{ form.password.errors[0] }}
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-success" type="submit">S'inscrire</button>
                                </div>

                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}